import http from 'node:http';
import crypto from 'node:crypto';
import pg from 'pg';
const {Pool}=pg;

const PORT=Number(process.env.PORT||3000);
const BOT_TOKEN=process.env.BOT_TOKEN||process.env.maison_aurea_bot_token||'';
const APP_URL=(process.env.PUBLIC_APP_URL||'https://maison-aurea2-1.onrender.com').replace(/\/$/,'');
const CREATOR_ID=String(process.env.CREATOR_TELEGRAM_USER_ID||'7519855566');
const WHATSAPP_NUMBER=String(process.env.WHATSAPP_NUMBER||'5355720394').replace(/\D/g,'');
const SUPPORT_EMAIL=String(process.env.SUPPORT_EMAIL||'nunezyenis05@gmail.com');
const PAYMENT_INFO=String(process.env.PAYMENT_INFO||'');
const WEBHOOK_SECRET=String(process.env.TELEGRAM_WEBHOOK_SECRET||'');
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;

const CATALOG={
 mining_packages:[
  {id:'initial',name:'Inicial',price_cup:500,diamonds:100,duration_days:3,reference_reward_diamonds:120},
  {id:'basic',name:'Básico',price_cup:2500,diamonds:500,duration_days:4,reference_reward_diamonds:650},
  {id:'large',name:'Grande',price_cup:5000,diamonds:1000,duration_days:5,reference_reward_diamonds:1350},
  {id:'premium',name:'Premium',price_cup:12500,diamonds:2500,duration_days:6,reference_reward_diamonds:3500},
  {id:'maximum',name:'Máximo',price_cup:25000,diamonds:5000,duration_days:7,reference_reward_diamonds:7500}
 ],
 memberships:[
  {id:'bronze',name:'Bronce',price_diamonds:100,duration_days:3,bonus_percent:5},
  {id:'silver',name:'Plata',price_diamonds:250,duration_days:4,bonus_percent:10},
  {id:'gold',name:'Oro',price_diamonds:500,duration_days:5,bonus_percent:20},
  {id:'platinum',name:'Platino',price_diamonds:1000,duration_days:6,bonus_percent:35},
  {id:'diamond',name:'Diamante',price_diamonds:2500,duration_days:7,bonus_percent:50}
 ],
 accelerators:[
  {id:'quartz',name:'Cuarzo',price_diamonds:100,speed_multiplier:2},
  {id:'ruby',name:'Rubí',price_diamonds:150,speed_multiplier:3},
  {id:'sapphire',name:'Zafiro',price_diamonds:200,speed_multiplier:4},
  {id:'supercluster',name:'Supercluster',price_diamonds:250,speed_multiplier:6},
  {id:'titan_reactor',name:'Reactor Titán',price_diamonds:300,instant_complete:true}
 ]
};
const STARTER={id:'starter',name:'Bono inicial',price_cup:0,diamonds:5,duration_minutes:30,reference_reward_cup:25,starter:true};

const SCHEMA=`
CREATE TABLE IF NOT EXISTS users(id bigserial primary key,telegram_user_id text unique not null,username text,first_name text,referral_code text unique not null,referred_by text,welcome_bonus_granted boolean not null default false,starter_bonus_granted boolean not null default false,suspended boolean not null default false,created_at timestamptz not null default now());
ALTER TABLE users ADD COLUMN IF NOT EXISTS welcome_bonus_granted boolean not null default false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS starter_bonus_granted boolean not null default false;
CREATE TABLE IF NOT EXISTS wallets(user_id bigint primary key references users(id),purchased_diamonds bigint not null default 0,promotional_diamonds bigint not null default 0,locked_diamonds bigint not null default 0,pending_cup bigint not null default 0,available_cup bigint not null default 0,paid_cup bigint not null default 0);
CREATE TABLE IF NOT EXISTS orders(id bigserial primary key,order_no text unique not null,user_id bigint not null references users(id),kind text not null,catalog_id text not null,amount_cup bigint not null default 0,diamonds bigint not null default 0,operation_no text,proof_url text,status text not null default 'pending_payment',snapshot jsonb,created_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS mining_sessions(id bigserial primary key,user_id bigint not null references users(id),package_id text not null,started_at timestamptz not null,ends_at timestamptz not null,status text not null default 'running',snapshot jsonb);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_mining ON mining_sessions(user_id) WHERE status='running';
CREATE TABLE IF NOT EXISTS card_entries(id bigserial primary key,user_id bigint not null references users(id),draw_key text not null,card text not null,created_at timestamptz not null default now(),unique(user_id,draw_key));
CREATE TABLE IF NOT EXISTS withdrawals(id bigserial primary key,request_no text unique not null,user_id bigint not null references users(id),amount_cup bigint not null,destination text not null,status text not null default 'requested',created_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS entitlements(id bigserial primary key,user_id bigint not null references users(id),kind text not null,catalog_id text not null,starts_at timestamptz not null default now(),ends_at timestamptz,status text not null default 'active',unique(user_id,kind,catalog_id,starts_at));
CREATE TABLE IF NOT EXISTS audit_log(id bigserial primary key,actor_telegram_id text,action text not null,target_type text,target_id text,details jsonb,created_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS referral_rewards(id bigserial primary key,referrer_user_id bigint not null references users(id),referred_user_id bigint unique not null references users(id),reward_diamonds bigint not null default 50,created_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS support_tickets(id bigserial primary key,user_id bigint not null references users(id),message text not null,channel text not null default 'whatsapp',status text not null default 'open',created_at timestamptz not null default now());`;

async function db(sql,params=[]){if(!pool)throw Error('database_unavailable');return pool.query(sql,params)}
async function init(){if(pool)await db(SCHEMA)}
function out(res,status,data,type='application/json'){res.statusCode=status;res.setHeader('content-type',type+'; charset=utf-8');res.end(type==='application/json'?JSON.stringify(data):data)}
function no(prefix){return prefix+'-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
async function body(req){let s='';for await(const c of req)s+=c;try{return s?JSON.parse(s):{}}catch{return{}}}
function telegramUser(raw){try{const q=new URLSearchParams(raw||'');const hash=q.get('hash');if(!hash||!BOT_TOKEN)return null;q.delete('hash');const check=[...q.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const secret=crypto.createHmac('sha256','WebAppData').update(BOT_TOKEN).digest();const good=crypto.createHmac('sha256',secret).update(check).digest('hex');if(!crypto.timingSafeEqual(Buffer.from(good),Buffer.from(hash)))return null;return{...JSON.parse(q.get('user')||'{}'),start_param:q.get('start_param')||''}}catch{return null}}
async function ensureUser(tg,ref=''){if(!tg?.id)return null;let r=await db('select * from users where telegram_user_id=$1',[String(tg.id)]);if(r.rowCount){const u=r.rows[0];await db('insert into wallets(user_id) values($1) on conflict(user_id) do nothing',[u.id]);if(!u.starter_bonus_granted){await db('update wallets set promotional_diamonds=promotional_diamonds+5 where user_id=$1',[u.id]);await db('update users set welcome_bonus_granted=true,starter_bonus_granted=true where id=$1',[u.id]);u.starter_bonus_granted=true}if(ref&&!u.referred_by){const rr=await db('select id from users where referral_code=$1 and telegram_user_id<>$2',[ref,String(tg.id)]);if(rr.rowCount)await db('update users set referred_by=$1 where id=$2',[ref,u.id])}return u}
 const code=crypto.randomBytes(5).toString('hex').toUpperCase();let referrer=null;if(ref){const x=await db('select id,telegram_user_id,username from users where referral_code=$1 and telegram_user_id<>$2',[ref,String(tg.id)]);if(x.rowCount)referrer=x.rows[0]}
 r=await db('insert into users(telegram_user_id,username,first_name,referral_code,referred_by,welcome_bonus_granted,starter_bonus_granted) values($1,$2,$3,$4,$5,true,true) returning *',[String(tg.id),tg.username||null,tg.first_name||'',code,referrer?ref:null]);await db('insert into wallets(user_id,promotional_diamonds) values($1,5)',[r.rows[0].id]);if(referrer&&CREATOR_ID)try{await telegram('sendMessage',{chat_id:CREATOR_ID,text:`🤝 Nuevo referido\nUsuario: @${tg.username||'sin_usuario'}\nID: ${tg.id}\nCódigo usado: ${ref}`})}catch(e){}return r.rows[0]}
async function auth(req){const tg=telegramUser(req.headers['x-telegram-init-data']||'');if(!tg)return null;return ensureUser(tg,tg.start_param)}
function item(kind,id){return CATALOG[kind==='membership'?'memberships':kind==='accelerator'?'accelerators':'mining_packages'].find(x=>x.id===id)}
function wa(text){return WHATSAPP_NUMBER?'https://wa.me/'+WHATSAPP_NUMBER+'?text='+encodeURIComponent(text):''}
function orderWa(o){return wa(`Solicitud de compra Maison Aurea\nOrden: ${o.order_no}\nProducto: ${o.kind} ${o.catalog_id}\nMonto: ${o.amount_cup} CUP\nDiamantes: ${o.diamonds}\n\n${PAYMENT_INFO}\n\nDespués de pagar, envía por este WhatsApp la captura de pantalla, tu número telefónico y el número de operación. Atención estimada: 30 minutos a 1 hora según la conexión.`)}
function withdrawalWa(w){return wa(`Solicitud de retiro Maison Aurea\nRetiro: ${w.request_no}\nUsuario: @${w.username||'sin_usuario'}\nID de Telegram: ${w.telegram_user_id}\nMonto: ${w.amount_cup} CUP\nDestino: ${w.destination||'no indicado'}`)}
async function telegram(method,payload){if(!BOT_TOKEN)throw Error('telegram_unavailable');const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!j.ok)throw Error(j.description||'telegram_error');return j.result}
async function notifyOrder(o){if(!CREATOR_ID)return;try{await telegram('sendMessage',{chat_id:CREATOR_ID,text:`🛒 Nueva compra\nOrden: ${o.order_no}\nProducto: ${o.kind} ${o.catalog_id}\nMonto: ${o.amount_cup} CUP\nDiamantes: ${o.diamonds}`,reply_markup:{inline_keyboard:[[{text:'✅ Aprobar',callback_data:'approve:'+o.order_no},{text:'❌ Rechazar',callback_data:'reject:'+o.order_no}]]}})}catch(e){console.error('order_notice',e.message)}}
async function notifyWithdrawal(w){if(!CREATOR_ID)return;try{await telegram('sendMessage',{chat_id:CREATOR_ID,text:`💸 Nuevo retiro\n${w.request_no}\nUsuario: @${w.username||'sin_usuario'}\nMonto: ${w.amount_cup} CUP\nDestino: ${w.destination||'no indicado'}`})}catch(e){console.error('withdrawal_notice',e.message)}}
async function rewardReferral(referredId){const r=(await db('select u.referred_by,ref.id referrer_id,ref.telegram_user_id from users u left join users ref on ref.referral_code=u.referred_by where u.id=$1',[referredId])).rows[0];if(!r?.referrer_id)return;if((await db('select id from referral_rewards where referred_user_id=$1',[referredId])).rowCount)return;const x=await db('insert into referral_rewards(referrer_user_id,referred_user_id,reward_diamonds) values($1,$2,50) on conflict(referred_user_id) do nothing returning id',[r.referrer_id,referredId]);if(x.rowCount){await db('update wallets set promotional_diamonds=promotional_diamonds+50 where user_id=$1',[r.referrer_id]);try{await telegram('sendMessage',{chat_id:r.telegram_user_id,text:'🎁 Tu referido completó su primera compra aprobada. Se acreditaron 50 diamantes promocionales.'})}catch(e){}}}
async function audit(actor,action,targetType,targetId,details){try{await db('insert into audit_log(actor_telegram_id,action,target_type,target_id,details) values($1,$2,$3,$4,$5)',[actor?String(actor):null,action,targetType||null,targetId?String(targetId):null,details?JSON.stringify(details):null])}catch(e){console.error('audit_log',e.message)}}
async function approveOrder(o,actorId){await db("update orders set status='approved' where order_no=$1 and status in ('pending_payment','under_review')",[o.order_no]);if(o.kind==='mining'){await db('update wallets set purchased_diamonds=purchased_diamonds+$1 where user_id=$2',[o.diamonds,o.user_id])}else{const c=item(o.kind,o.catalog_id);const days=c?.duration_days||7;await db("insert into entitlements(user_id,kind,catalog_id,ends_at) values($1,$2,$3,now()+($4||' days')::interval)",[o.user_id,o.kind,o.catalog_id,String(days)])}await rewardReferral(o.user_id);await audit(actorId,'order_approved','order',o.order_no,{kind:o.kind,catalog_id:o.catalog_id,amount_cup:o.amount_cup,diamonds:o.diamonds})}
async function rejectOrder(o,actorId){await db("update orders set status='rejected' where order_no=$1 and status in ('pending_payment','under_review')",[o.order_no]);await audit(actorId,'order_rejected','order',o.order_no,{kind:o.kind,catalog_id:o.catalog_id})}
function drawSlot(){const hav=new Date(new Date().toLocaleString('en-US',{timeZone:'America/Havana'}));const h=hav.getHours(),date=hav.toISOString().slice(0,10);if(h>=8&&h<12)return date+'-AM';if(h>=14&&h<22)return date+'-PM';return null}
function keyboard(chat){const b=[[['⛏️ Minar','mining'],['🃏 Cartas','cards']],[['💎 Comprar','diamonds'],['👛 Billetera','wallet']],[['🤝 Referidos','referrals'],['👑 Membresías','members']],[['⚡ Aceleradores','accelerators'],['🆘 Soporte','support']],[['⚙️ Ajustes','settings'],['📋 Reglas','rules']]];if(String(chat)===CREATOR_ID)b.push([['🔐 Panel de creadora','admin']]);return{keyboard:b.map(row=>row.map(([text,screen])=>({text,web_app:{url:`${APP_URL}/app?screen=${screen}&v=20260912-rebuild`}}))),resize_keyboard:true,is_persistent:true}}
async function bot(update){if(update?.callback_query){const q=update.callback_query;if(String(q.from?.id)!==CREATOR_ID){await telegram('answerCallbackQuery',{callback_query_id:q.id,text:'No autorizado',show_alert:true});return}const [action,orderNo]=String(q.data||'').split(':');const r=await db("select * from orders where order_no=$1 and status in ('pending_payment','under_review')",[orderNo]);if(!r.rowCount){await telegram('answerCallbackQuery',{callback_query_id:q.id,text:'Orden no disponible',show_alert:true});return}const o=r.rows[0];if(action==='approve'){await approveOrder(o,q.from.id);await telegram('answerCallbackQuery',{callback_query_id:q.id,text:'Orden aprobada'});await telegram('editMessageReplyMarkup',{chat_id:q.message.chat.id,message_id:q.message.message_id,reply_markup:{inline_keyboard:[]}})}else if(action==='reject'){await rejectOrder(o,q.from.id);await telegram('answerCallbackQuery',{callback_query_id:q.id,text:'Orden rechazada'});await telegram('editMessageReplyMarkup',{chat_id:q.message.chat.id,message_id:q.message.message_id,reply_markup:{inline_keyboard:[]}})}return}
 const m=update?.message||update;if(!m?.chat?.id)return;const chat=m.chat.id,text=String(m.text||'').trim();if(text.startsWith('/start')){await ensureUser(m.from,String(text.split(/\s+/)[1]||''));await telegram('sendMessage',{chat_id:chat,text:'💎 Maison Aurea\n\nTeclado actualizado. Cada botón abre directamente su sección.',reply_markup:{remove_keyboard:true}});await telegram('sendMessage',{chat_id:chat,text:'Menú principal',reply_markup:keyboard(chat)});return}await telegram('sendMessage',{chat_id:chat,text:'Selecciona una sección:',reply_markup:keyboard(chat)})}

async function api(req,res){const path=new URL(req.url,'http://local').pathname;if(req.method==='GET'&&path==='/api/catalog')return out(res,200,CATALOG);const u=await auth(req);if(!u)return out(res,401,{error:'Abre Maison Aurea desde Telegram.'});
 if(path.startsWith('/api/admin/')){if(String(u.telegram_user_id)!==CREATOR_ID)return out(res,403,{error:'No autorizado'});
  if(req.method==='GET'&&path==='/api/admin/orders')return out(res,200,(await db("select order_no,user_id,kind,catalog_id,amount_cup,diamonds,status,operation_no,created_at from orders where status in ('pending_payment','under_review') order by id desc limit 200")).rows);
  if(req.method==='GET'&&path==='/api/admin/withdrawals')return out(res,200,(await db("select request_no,user_id,amount_cup,destination,status,created_at from withdrawals where status='requested' order by id desc limit 200")).rows);
  if(req.method==='GET'&&path==='/api/admin/users')return out(res,200,(await db('select id,telegram_user_id,username,first_name,referred_by,suspended,created_at from users order by id desc limit 200')).rows);
  if(req.method==='GET'&&path==='/api/admin/audit')return out(res,200,(await db('select actor_telegram_id,action,target_type,target_id,details,created_at from audit_log order by id desc limit 200')).rows);
  if(req.method==='POST'&&path==='/api/admin/orders/approve'){const b=await body(req);const r=await db("select * from orders where order_no=$1 and status in ('pending_payment','under_review')",[b.order_no]);if(!r.rowCount)return out(res,409,{error:'Orden no disponible'});await approveOrder(r.rows[0],u.telegram_user_id);return out(res,200,{ok:true})}
  if(req.method==='POST'&&path==='/api/admin/orders/reject'){const b=await body(req);const r=await db("select * from orders where order_no=$1 and status in ('pending_payment','under_review')",[b.order_no]);if(!r.rowCount)return out(res,409,{error:'Orden no disponible'});await rejectOrder(r.rows[0],u.telegram_user_id);return out(res,200,{ok:true})}
  if(req.method==='POST'&&path==='/api/admin/withdrawals/paid'){const b=await body(req);const r=await db("update withdrawals set status='paid' where request_no=$1 and status='requested' returning *",[b.request_no]);if(!r.rowCount)return out(res,409,{error:'Retiro no disponible'});await db('update wallets set pending_cup=pending_cup-$1,paid_cup=paid_cup+$1 where user_id=$2',[r.rows[0].amount_cup,r.rows[0].user_id]);await audit(u.telegram_user_id,'withdrawal_paid','withdrawal',b.request_no,{amount_cup:r.rows[0].amount_cup});return out(res,200,{ok:true})}
  return out(res,404,{error:'Ruta no encontrada'})}
 if(req.method==='GET'&&path==='/api/me'){const due=(await db("select id,snapshot from mining_sessions where user_id=$1 and status='running' and ends_at<=now()",[u.id])).rows;for(const x of due){const done=await db("update mining_sessions set status='completed' where id=$1 and status='running' returning id",[x.id]);if(done.rowCount&&x.snapshot?.starter)await db('update wallets set locked_diamonds=greatest(0,locked_diamonds-5),available_cup=available_cup+25 where user_id=$1',[u.id])}const w=(await db('select * from wallets where user_id=$1',[u.id])).rows[0];const m=(await db("select * from mining_sessions where user_id=$1 and status='running' order by id desc limit 1",[u.id])).rows[0]||null;return out(res,200,{user:{first_name:u.first_name,username:u.username,telegram_user_id:u.telegram_user_id,referral_code:u.referral_code,is_creator:String(u.telegram_user_id)===CREATOR_ID},wallet:w,mining:m})}
 if(req.method==='POST'&&path==='/api/orders'){const b=await body(req);const kind=b.kind==='membership'?'membership':b.kind==='accelerator'?'accelerator':'mining';const c=item(kind,b.catalog_id);if(!c)return out(res,400,{error:'Producto inválido'});const o={order_no:no('ORD'),kind,catalog_id:b.catalog_id,amount_cup:c.price_cup||0,diamonds:c.diamonds||c.price_diamonds||0};await db('insert into orders(order_no,user_id,kind,catalog_id,amount_cup,diamonds,snapshot) values($1,$2,$3,$4,$5,$6,$7)',[o.order_no,u.id,o.kind,o.catalog_id,o.amount_cup,o.diamonds,c]);notifyOrder(o);return out(res,201,{...o,status:'pending_payment',whatsapp_url:orderWa(o)})}
 if(req.method==='POST'&&path==='/api/orders/proof'){const b=await body(req);const r=await db("update orders set operation_no=$1,proof_url=$2,status='under_review' where order_no=$3 and user_id=$4 and status='pending_payment' returning order_no,status",[b.operation_no||null,b.proof_url||null,b.order_no,u.id]);return r.rowCount?out(res,200,r.rows[0]):out(res,409,{error:'Orden no editable'})}
 if(req.method==='GET'&&path==='/api/orders')return out(res,200,(await db('select order_no,kind,catalog_id,amount_cup,diamonds,status,operation_no,created_at from orders where user_id=$1 order by id desc limit 100',[u.id])).rows);
 if(req.method==='POST'&&path==='/api/mining/start'){const b=await body(req);const c=b.package_id==='starter'?STARTER:item('mining',b.package_id);if(!c)return out(res,400,{error:'Paquete inválido'});if((await db("select id from mining_sessions where user_id=$1 and status='running'",[u.id])).rowCount)return out(res,409,{error:'Ya tienes una minería activa'});const w=await db('update wallets set purchased_diamonds=purchased_diamonds-least(purchased_diamonds,$1),promotional_diamonds=promotional_diamonds-greatest(0,$1-purchased_diamonds),locked_diamonds=locked_diamonds+$1 where user_id=$2 and purchased_diamonds+promotional_diamonds>=$1 returning *',[c.diamonds,u.id]);if(!w.rowCount)return out(res,400,{error:'Saldo de diamantes insuficiente'});const start=new Date(),end=new Date(start.getTime()+(c.duration_minutes?c.duration_minutes*60000:c.duration_days*86400000));const r=await db('insert into mining_sessions(user_id,package_id,started_at,ends_at,status,snapshot) values($1,$2,$3,$4,\'running\',$5) returning *',[u.id,c.id,start,end,{...c,starter:!!c.starter}]);return out(res,201,r.rows[0])}
 if(req.method==='POST'&&path==='/api/cards/enter'){const b=await body(req);const card=String(b.card||'').trim();if(!card)return out(res,400,{error:'Selecciona una carta'});const slot=drawSlot();if(!slot)return out(res,409,{error:'El sorteo de cartas está cerrado en este horario (08:00–12:00 y 14:00–22:00, hora de La Habana).'});if((await db('select id from card_entries where user_id=$1 and draw_key=$2',[u.id,slot])).rowCount)return out(res,409,{error:'Ya participaste en el sorteo actual.'});const w=await db('update wallets set purchased_diamonds=purchased_diamonds-least(purchased_diamonds,100),promotional_diamonds=promotional_diamonds-greatest(0,100-purchased_diamonds) where user_id=$1 and purchased_diamonds+promotional_diamonds>=100 returning *',[u.id]);if(!w.rowCount)return out(res,400,{error:'Diamantes insuficientes (se requieren 100).'});await db('insert into card_entries(user_id,draw_key,card) values($1,$2,$3)',[u.id,slot,card]);await audit(u.telegram_user_id,'card_entry','card',card,{draw_key:slot});return out(res,201,{ok:true,draw_key:slot,card})}
 if(req.method==='GET'&&path==='/api/referrals'){const code=(await db('select referral_code from users where id=$1',[u.id])).rows[0].referral_code;const invited=(await db('select username,created_at from users where referred_by=$1 order by created_at desc',[code])).rows;const rewards=(await db('select coalesce(sum(reward_diamonds),0)::int total from referral_rewards where referrer_user_id=$1',[u.id])).rows[0].total;return out(res,200,{code,link:`https://t.me/MaisonAureaGameBot?start=${code}`,share_text:`💎 Entra a Maison Aurea con mi código ${code} y abre el bot para comenzar.`,invited,rewarded_diamonds:rewards})}
 if(req.method==='GET'&&path==='/api/support'){const template=`🆘 Soporte Maison Aurea\nUsuario: @${u.username||'sin_usuario'}\nID de Telegram: ${u.telegram_user_id}\n\nDescribe tu problema, número de orden o retiro.\n\nAtención estimada: 30 minutos a 1 hora según la conexión.`;return out(res,200,{phone:'+5355720394',email:SUPPORT_EMAIL,template,whatsapp_url:wa(template)})}
 if(req.method==='POST'&&path==='/api/support'){const b=await body(req);const text=String(b.message||'').trim();if(!text)return out(res,400,{error:'Escribe tu solicitud'});await db('insert into support_tickets(user_id,message) values($1,$2)',[u.id,text]);return out(res,201,{ok:true})}
 if(req.method==='POST'&&path==='/api/withdrawals'){const b=await body(req),amount=Number(b.amount_cup);if(!Number.isInteger(amount)||amount<=0)return out(res,400,{error:'Monto inválido'});const w=await db('update wallets set available_cup=available_cup-$1,pending_cup=pending_cup+$1 where user_id=$2 and available_cup>=$1 returning *',[amount,u.id]);if(!w.rowCount)return out(res,400,{error:'Saldo CUP insuficiente'});const request_no=no('RET'),destination=String(b.destination||'');await db('insert into withdrawals(request_no,user_id,amount_cup,destination) values($1,$2,$3,$4)',[request_no,u.id,amount,destination]);const x={request_no,amount_cup:amount,destination,username:u.username,telegram_user_id:u.telegram_user_id};notifyWithdrawal(x);await audit(u.telegram_user_id,'withdrawal_requested','withdrawal',request_no,{amount_cup:amount,destination});return out(res,201,{request_no,whatsapp_url:withdrawalWa(x)})}
 return out(res,404,{error:'Ruta no encontrada'})}

let HTML='';
async function main(){try{HTML=await (await import('node:fs/promises')).readFile(new URL('./public/index.html',import.meta.url),'utf8')}catch(e){HTML='<h1>Maison Aurea</h1>'}await init();const server=http.createServer(async(req,res)=>{try{const p=new URL(req.url,'http://local').pathname;if(p==='/health')return out(res,200,{ok:true,app:'Maison Aurea',database:!!pool,telegram:!!BOT_TOKEN});if(req.method==='POST'&&p==='/telegram/webhook'){if(WEBHOOK_SECRET&&req.headers['x-telegram-bot-api-secret-token']!==WEBHOOK_SECRET)return out(res,401,{error:'unauthorized'});await bot(await body(req));return out(res,200,{ok:true})}if(req.method==='GET'&&(p==='/'||p==='/app'))return out(res,200,HTML,'text/html');if(p.startsWith('/api/'))return api(req,res);return out(res,404,{error:'not_found'})}catch(e){console.error(e);return out(res,500,{error:'internal_error'})}});server.listen(PORT,()=>console.log('Maison Aurea listening on '+PORT))}
main().catch(e=>{console.error(e);process.exit(1)})
